version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ./:/src
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      POSTGRES_URL: postgres://erickwendel:mysecret@postgres/ew007
    links:
      - postgres

    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: erickwendel
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: ew007

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres
